apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: udp-server
  template:
    metadata:
      labels:
        name: udp-server
    spec:
      containers:
      - name: udp-server
        image: quay.io/rhn-support-gizzi/udp-server:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 10001
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-server-service
  labels:
    app: udp-server
spec:
  type: LoadBalancer
  #allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  #sessionAffinity: ClientIP
  ports:
  - port: 20001
    protocol: UDP
    targetPort: 10001
  selector:
    name: udp-server
