apiVersion: v1
kind: Service
metadata:
  name: udp-server-service
  labels:
    app: udp-server
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  #internalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 120
  ports:
  - port: 10001
    protocol: UDP
    targetPort: 10001
  selector:
    name: udp-server
